// ---------------------------------------------------------------------------
// Shared types for the Sorell application
// ---------------------------------------------------------------------------

/** A single newsletter article generated by Claude. */
export interface Article {
  tag: string;
  title: string;
  hook: string;
  content: string;
  summary?: string;
  source: string;
  url: string;
  featured: boolean;
  image_url?: string | null;
}

/** A key figure extracted from newsletter articles. */
export interface KeyFigure {
  value: string;
  label: string;
  context: string;
}

/** The full JSON content stored in a newsletter record. */
export interface NewsletterContent {
  editorial: string;
  key_figures: KeyFigure[];
  articles: Article[];
}

/** A newsletter recipient. */
export interface Recipient {
  id?: string;
  user_id: string;
  email: string;
  name: string;
}

/** A topic item in the newsletter configuration. */
export interface Topic {
  label: string;
  enabled: boolean;
}

/** Demo article type used by DemoGenerator. */
export interface DemoArticle {
  tag: string;
  title: string;
  summary: string;
  source: string;
  featured?: boolean;
  image_url?: string | null;
}
